4.4.5
YunoHost-Apps/yeswiki_ynh pull request #105
Opened 2024-10-31 20:25 UTC by ericgaspar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2024-10-31 20:26 UTC, ericgaspar commented
!testme

2024-11-01 06:04 UTC, mrflos commented
!testme

2024-11-01 16:19 UTC, ericgaspar commented
!testme

2024-11-04 10:48 UTC, mrflos commented
!testme again

2024-11-08 09:24 UTC, mrflos commented
!testme

2024-11-10 11:36 UTC, ericgaspar commented
!testme

2024-11-10 21:17 UTC, Lab-8916100448256 commented
!testme please, pretty please, with a cherry on top

2024-11-10 21:18 UTC, Lab-8916100448256 commented
!testme
please, pretty please, with a cherry on top

2024-11-10 21:34 UTC, Lab-8916100448256 requested changes

2024-11-10 21:34 UTC, Lab-8916100448256 commented on scripts/backup
> +if [ -d "/etc/sudoers.d/$app" ]; then
this should be `if [ -f ...`
/etc/sudoers.d/$app is a file not a directory

2024-11-11 08:50 UTC, merged